language: haskell
cache:
  directories:
    - node_modules
    - elm-stuff
branches:
  only:
    - master
install:
  - npm install -g elm@0.18.0 uglify-js@2.6.1
  - elm-package install -y
script:
  - bash ./gh-pages.sh
notifications:
  email:
    recipients:
      - andrey.kuzmin@zalando.de
      - vignesh.shamugam@zalando.de
    on_failure: always
